from_mixamo = {
    "Head": ["nose", "left_eye", "right_eye", "left_ear", "right_ear", "mouth_left", "mouth_right", "left_eye_inner",
             "right_eye_inner", "left_eye_outer", "right_eye_outer"],
    "LeftShoulder": ["left_shoulder"],
    "RightShoulder": ["right_shoulder"],
    "LeftArm": ["left_elbow"],
    "RightArm": ["right_elbow"],
    "LeftHand": ["left_wrist"],
    "RightHand": ["right_wrist"],
    "LeftHandPinky4": ["left_pinky"],
    "RightHandPinky4": ["right_pinky"],
    "LeftHandIndex4": ["left_index"],
    "RightHandIndex4": ["right_index"],
    "LeftHandThumb4": ["left_thumb"],
    "RightHandThumb4": ["right_thumb"],
    "LeftUpLeg": ["left_hip"],
    "RightUpLeg": ["right_hip"],
    "LeftLeg": ["left_knee"],
    "RightLeg": ["right_knee"],
    "LeftFoot": ["left_ankle", "left_heel"],
    "RightFoot": ["right_ankle", "right_heel"],
    "LeftToe_End": ["left_foot_index"],
    "RightToe_End": ["right_foot_index"],
}

# to_mixamo = {
#     "nose": "Head",
#     "left_eye_inner": None,
#     "left_eye": "Head",
#     "left_eye_outer": None,
#     "right_eye_inner": None,
#     "right_eye": "Head",
#     "right_eye_outer": None,
#     "left_ear": "Head",
#     "right_ear": "Head",
#     "mouth_left": "Head",
#     "mouth_right": "Head",
#     "left_shoulder": "LeftShoulder",
#     "right_shoulder": "RightShoulder",
#     "left_elbow": "LeftArm",
#     "right_elbow": "RightArm",
#     "left_wrist": "LeftHand",
#     "right_wrist": "RightHand",
#     "left_pinky": "LeftHandPinky4",
#     "right_pinky": "RightHandPinky4",
#     "left_index": "LeftHandIndex4",
#     "right_index": "RightHandIndex4",
#     "left_thumb": "LeftHandThumb4",
#     "right_thumb": "RightHandThumb4",
#     "left_hip": "LeftUpLeg",
#     "right_hip": "RightUpLeg",
#     "left_knee": "LeftLeg",
#     "right_knee": "RightLeg",
#     "left_ankle": "LeftFoot",
#     "right_ankle": "RightFoot",
#     "left_heel": "LeftFoot",
#     "right_heel": "RightFoot",
#     "left_foot_index": "LeftToe_End",
#     "right_foot_index": "RightToe_End",
# }
